### ISSUE TITLE
no build script here

### ISSUE THREAD

**Issue by zaxebo1** [FluidIdeas/aryalinux#12]
all i see is README.md and LICENSE. There is no source code of build scripts here( i was directed here by a link in "footer message" at http://aryalinux.org )

Can you provide the link to source code (build scripts etc)?

**Comment by FluidIdeas** [comment]
Hi,

Actually the build scripts are checked into branches corresponding to the
version of aryalinux you are building. For instance the build scripts for
2016.08 would be available in the 2016.08 branch. You need to check out the
branch in order to get the build scripts:

git checkout 2016.08

Regards
Chandrakant

**Comment by zaxebo1** [comment]
thanks for the info. you may close this issue

====

additional:
you people may like to contribute/join to India's own linux distribution's team
https://www.bosslinux.in/
https://en.wikipedia.org/wiki/Bharat_Operating_System_Solutions

====
